# === Modernized Postfix + OpenDKIM Playbook ===

- name: "Postfix: Copy postfix config file to /etc/postfix/master.cf"
  become: yes
  ansible.builtin.copy:
    src: "master.cf"
    dest: "/etc/postfix/master.cf"

- name: "Postfix: Copy postfix header checks to /etc/postfix/header_checks"
  become: yes
  ansible.builtin.copy:
    src: "header_checks"
    dest: "/etc/postfix/header_checks"

- name: "Postfix: Configure base postfix settings"
  become: yes
  ansible.builtin.command: "postconf -e {{ item.key }}={{ item.value }}"
  loop: "{{ lookup('dict', postfix_config) }}"
  changed_when: false

- name: "Postfix: Modern TLS settings"
  become: yes
  ansible.builtin.command: "postconf -e {{ item.key }}={{ item.value }}"
  loop:
    - { key: 'smtpd_tls_security_level', value: 'may' }
    - { key: 'smtp_tls_security_level', value: 'may' }
    - { key: 'smtpd_tls_auth_only', value: 'yes' }
    - { key: 'smtpd_tls_protocols', value: '!SSLv2, !SSLv3, !TLSv1, !TLSv1.1' }
    - { key: 'smtpd_tls_mandatory_protocols', value: '!SSLv2, !SSLv3, !TLSv1, !TLSv1.1' }
    - { key: 'smtp_tls_protocols', value: '!SSLv2, !SSLv3, !TLSv1, !TLSv1.1' }
    - { key: 'smtpd_tls_ciphers', value: 'high' }
    - { key: 'smtpd_tls_mandatory_ciphers', value: 'high' }
    - { key: 'smtpd_tls_exclude_ciphers', value: 'aNULL, MD5' }
    - { key: 'smtp_tls_note_starttls_offer', value: 'yes' }
  changed_when: false

- name: "Postfix: Tighten relay restrictions"
  become: yes
  ansible.builtin.command: "postconf -e smtpd_relay_restrictions='permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination'"
  changed_when: false

- name: "Postfix: Configure milter integration"
  become: yes
  ansible.builtin.command: "postconf -e {{ item }}"
  loop:
    - "milter_default_action=accept"
    - "smtpd_milters=unix:/var/run/opendkim/opendkim.sock"
    - "non_smtpd_milters=unix:/var/run/opendkim/opendkim.sock"
  changed_when: false

- name: "Postfix: copy the template for email forwards"
  become: yes
  ansible.builtin.template:
    src: "virtual.j2"
    dest: "/etc/postfix/virtual"

- name: "Postfix: Add {{ domain_name }} to /etc/mailname"
  become: yes
  ansible.builtin.lineinfile:
    dest: /etc/mailname
    create: yes
    line: "{{ domain_name }}"
    state: present

- name: "OpenDKIM: Copy opendkim config file to /etc/opendkim.conf"
  become: yes
  ansible.builtin.copy:
    src: "opendkim.conf"
    dest: "/etc/opendkim.conf"

- name: "OpenDKIM: Create /etc/opendkim/keys/{{ domain_name }} if it does not exist"
  become: yes
  ansible.builtin.file:
    path: "/etc/opendkim/keys/{{ domain_name }}"
    state: directory
    mode: '0755'

- name: "OpenDKIM: Create opendkim keys"
  become: yes
  ansible.builtin.command: "opendkim-genkey -t -s mail -d {{ domain_name }}"
  args:
    chdir: "/etc/opendkim/keys/{{ domain_name }}"
    creates: "/etc/opendkim/keys/{{ domain_name }}/mail.txt"

- name: "OpenDKIM: Create the DNS entry for the DKIM keys"
  become: yes
  ansible.builtin.shell: |
    cat mail.txt | tr -d '\r\n\t\\"\ ' | cut -d"(" -f2 | cut -d ")" -f1 > /root/dkim.txt
  args:
    chdir: "/etc/opendkim/keys/{{ domain_name }}"
    creates: "/root/dkim.txt"

- name: "OpenDKIM: Change ownership of mail.private to opendkim:opendkim"
  become: yes
  ansible.builtin.file:
    path: "/etc/opendkim/keys/{{ domain_name }}/mail.private"
    owner: opendkim
    group: opendkim

- name: "OpenDKIM: Configure /etc/opendkim/KeyTable"
  become: yes
  ansible.builtin.lineinfile:
    dest: /etc/opendkim/KeyTable
    create: yes
    line: "mail._domainkey.{{ domain_name }} {{ domain_name }}:mail:/etc/opendkim/keys/{{ domain_name }}/mail.private"
    state: present

- name: "OpenDKIM: Configure /etc/opendkim/SigningTable"
  become: yes
  ansible.builtin.lineinfile:
    dest: /etc/opendkim/SigningTable
    create: yes
    line: "*@{{ domain_name }} mail._domainkey.{{ domain_name }}"
    state: present

- name: "OpenDKIM: Use Unix socket"
  become: yes
  ansible.builtin.lineinfile:
    dest: /etc/default/opendkim
    regexp: '^SOCKET='
    line: 'SOCKET="local:/var/run/opendkim/opendkim.sock"'
    create: yes

- name: "Ensure /var/spool/postfix/var/run/opendkim exists"
  become: yes
  ansible.builtin.file:
    path: "/var/spool/postfix/var/run/opendkim"
    state: directory
    owner: opendkim
    group: opendkim
    mode: '0755'

- name: "OpenDKIM: Configure /etc/opendkim/TrustedHosts"
  become: yes
  ansible.builtin.lineinfile:
    dest: /etc/opendkim/TrustedHosts
    create: yes
    line: '{{ item }}'
    state: present
  loop:
    - "{{ ansible_host }}"
    - "*.{{ domain_name }}"
    - "localhost"
    - "127.0.0.1"
    - "{{ internal_vpn_ip_space }}"

- name: "Postfix: Postmap /etc/postfix/header_checks"
  become: yes
  ansible.builtin.command: "postmap /etc/postfix/header_checks"
  changed_when: false

- name: "Postfix: Postmap /etc/postfix/virtual"
  become: yes
  ansible.builtin.command: "postmap /etc/postfix/virtual"
  changed_when: false

- name: "Postfix: Reload postfix"
  become: yes
  ansible.builtin.command: "postfix reload"
  changed_when: false

- name: "Restart Postfix and Opendkim"
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  become: yes
  loop:
    - postfix
    - opendkim
  changed_when: false

- name: "OpenDKIM: Load DKIM Configuration"
  become: yes
  ansible.builtin.slurp:
    src: /root/dkim.txt
  register: dkim_contents

- name: "SMTP Server: Create a DNS Template (including SPF and DMARC suggestions)"
  ansible.builtin.template:
    src: dns-config.j2
    dest: "{{ toolkit_directory }}/dns_config_{{ inventory_hostname }}.txt"

- name: Create local DNS-Config directory
  ansible.builtin.file:
    path: "{{ export_path }}/dns_configs/"
    state: directory
    recurse: yes
  delegate_to: localhost

- name: "Download the client profiles to {{ export_path }} directory"
  ansible.builtin.fetch:
    src: "{{ toolkit_directory }}/dns_config_{{ inventory_hostname }}.txt"
    dest: "{{ export_path }}/dns_configs/"
    flat: yes
